# Generated by Django 5.2.6 on 2025-10-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=10, null=True)),
                ('cholesterol_level', models.CharField(blank=True, max_length=10, null=True)),
                ('exercise_habits', models.CharField(blank=True, max_length=10, null=True)),
                ('smoking', models.CharField(blank=True, max_length=10, null=True)),
                ('family_heart_disease', models.CharField(blank=True, max_length=10, null=True)),
                ('diabetes', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('heart_disease_status', models.CharField(blank=True, max_length=10, null=True)),
                ('high_blood_pressure', models.CharField(blank=True, max_length=10, null=True)),
                ('low_hdl_cholesterol', models.CharField(blank=True, max_length=10, null=True)),
                ('high_ldl_cholesterol', models.CharField(blank=True, max_length=10, null=True)),
                ('alcohol_consumption', models.CharField(blank=True, max_length=10, null=True)),
                ('stress_level', models.CharField(blank=True, max_length=10, null=True)),
                ('sleep_hours', models.CharField(blank=True, max_length=10, null=True)),
                ('sugar_consumption', models.CharField(blank=True, max_length=10, null=True)),
                ('triglyceride_level', models.CharField(blank=True, max_length=10, null=True)),
                ('fasting_blood_sugar', models.CharField(blank=True, max_length=10, null=True)),
                ('crp_level', models.CharField(blank=True, max_length=10, null=True)),
                ('homocysteine_level', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'app_dados_teste',
            },
        ),
        migrations.CreateModel(
            name='DadosTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=10, null=True)),
                ('cholesterol_level', models.CharField(blank=True, max_length=10, null=True)),
                ('exercise_habits', models.CharField(blank=True, max_length=10, null=True)),
                ('smoking', models.CharField(blank=True, max_length=10, null=True)),
                ('family_heart_disease', models.CharField(blank=True, max_length=10, null=True)),
                ('diabetes', models.CharField(blank=True, max_length=10, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('high_blood_pressure', models.CharField(blank=True, max_length=10, null=True)),
                ('low_hdl_cholesterol', models.CharField(blank=True, max_length=10, null=True)),
                ('high_ldl_cholesterol', models.CharField(blank=True, max_length=10, null=True)),
                ('alcohol_consumption', models.CharField(blank=True, max_length=10, null=True)),
                ('stress_level', models.CharField(blank=True, max_length=10, null=True)),
                ('sleep_hours', models.CharField(blank=True, max_length=10, null=True)),
                ('sugar_consumption', models.CharField(blank=True, max_length=10, null=True)),
                ('triglyceride_level', models.CharField(blank=True, max_length=10, null=True)),
                ('fasting_blood_sugar', models.CharField(blank=True, max_length=10, null=True)),
                ('crp_level', models.CharField(blank=True, max_length=10, null=True)),
                ('heart_disease_status', models.CharField(choices=[('No', 'No'), ('Unknown', 'Unknown'), ('Yes', 'Yes')], default='Unknown', max_length=10)),
                ('homocysteine_level', models.CharField(blank=True, default='Unknown', max_length=10, null=True)),
            ],
            options={
                'db_table': 'app_dados_treino',
            },
        ),
    ]
