# Generated by Django 5.2.6 on 2025-09-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=10)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Unknown', 'Unknown')], max_length=10)),
                ('blood_pressure', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=10)),
                ('cholesterol_level', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=10)),
                ('exercise_habits', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium'), ('Unknown', 'Unknown')], max_length=10)),
                ('smoking', models.CharField(choices=[('No', 'No'), ('Unknown', 'Unknown'), ('Yes', 'Yes')], max_length=10)),
                ('family_heart_disease', models.CharField(choices=[('No', 'No'), ('Unknown', 'Unknown'), ('Yes', 'Yes')], max_length=10)),
                ('diabetes', models.CharField(choices=[('No', 'No'), ('Unknown', 'Unknown'), ('Yes', 'Yes')], max_length=10)),
                ('bmi', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=10)),
                ('high_blood_pressure', models.CharField(choices=[('No', 'No'), ('Unknown', 'Unknown'), ('Yes', 'Yes')], max_length=10)),
                ('low_hdl_cholesterol', models.CharField(choices=[('No', 'No'), ('Unknown', 'Unknown'), ('Yes', 'Yes')], max_length=10)),
                ('high_ldl_cholesterol', models.CharField(choices=[('No', 'No'), ('Unknown', 'Unknown'), ('Yes', 'Yes')], max_length=10)),
                ('alcohol_consumption', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium'), ('None', 'None'), ('Unknown', 'Unknown')], max_length=10)),
                ('stress_level', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium'), ('Unknown', 'Unknown')], max_length=10)),
                ('sleep_hours', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=10)),
                ('sugar_consumption', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium'), ('Unknown', 'Unknown')], max_length=10)),
                ('triglyceride_level', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=10)),
                ('fasting_blood_sugar', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=10)),
                ('crp_level', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=10)),
                ('homocysteine_level', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=10)),
                ('heart_disease_status', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Dados_treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=10)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Unknown', 'Unknown')], max_length=10)),
                ('blood_pressure', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=10)),
                ('cholesterol_level', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=10)),
                ('exercise_habits', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium'), ('Unknown', 'Unknown')], max_length=10)),
                ('smoking', models.CharField(choices=[('No', 'No'), ('Unknown', 'Unknown'), ('Yes', 'Yes')], max_length=10)),
                ('family_heart_disease', models.CharField(choices=[('No', 'No'), ('Unknown', 'Unknown'), ('Yes', 'Yes')], max_length=10)),
                ('diabetes', models.CharField(choices=[('No', 'No'), ('Unknown', 'Unknown'), ('Yes', 'Yes')], max_length=10)),
                ('bmi', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=10)),
                ('high_blood_pressure', models.CharField(choices=[('No', 'No'), ('Unknown', 'Unknown'), ('Yes', 'Yes')], max_length=10)),
                ('low_hdl_cholesterol', models.CharField(choices=[('No', 'No'), ('Unknown', 'Unknown'), ('Yes', 'Yes')], max_length=10)),
                ('high_ldl_cholesterol', models.CharField(choices=[('No', 'No'), ('Unknown', 'Unknown'), ('Yes', 'Yes')], max_length=10)),
                ('alcohol_consumption', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium'), ('None', 'None'), ('Unknown', 'Unknown')], max_length=10)),
                ('stress_level', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium'), ('Unknown', 'Unknown')], max_length=10)),
                ('sleep_hours', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=10)),
                ('sugar_consumption', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium'), ('Unknown', 'Unknown')], max_length=10)),
                ('triglyceride_level', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=10)),
                ('fasting_blood_sugar', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=10)),
                ('crp_level', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=10)),
                ('homocysteine_level', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=10)),
                ('heart_disease_status', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=3)),
            ],
        ),
    ]
