# Generated by Django 5.2.6 on 2025-10-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosteste',
            name='heart_disease_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
