# Generated by Django 5.2.6 on 2025-10-30 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_dadosteste_heart_disease_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('cholesterol_level', models.CharField(blank=True, max_length=20, null=True)),
                ('exercise_habits', models.CharField(blank=True, max_length=20, null=True)),
                ('smoking', models.CharField(blank=True, max_length=10, null=True)),
                ('family_heart_disease', models.CharField(blank=True, max_length=10, null=True)),
                ('diabetes', models.CharField(blank=True, max_length=10, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('high_blood_pressure', models.CharField(blank=True, max_length=10, null=True)),
                ('low_hdl_cholesterol', models.CharField(blank=True, max_length=10, null=True)),
                ('high_ldl_cholesterol', models.CharField(blank=True, max_length=10, null=True)),
                ('alcohol_consumption', models.CharField(blank=True, max_length=10, null=True)),
                ('stress_level', models.CharField(blank=True, max_length=10, null=True)),
                ('sleep_hours', models.CharField(blank=True, max_length=10, null=True)),
                ('sugar_consumption', models.CharField(blank=True, max_length=10, null=True)),
                ('triglyceride_level', models.CharField(blank=True, max_length=10, null=True)),
                ('fasting_blood_sugar', models.CharField(blank=True, max_length=10, null=True)),
                ('crp_level', models.CharField(blank=True, max_length=10, null=True)),
                ('homocysteine_level', models.CharField(blank=True, max_length=10, null=True)),
                ('risk_class', models.CharField(blank=True, max_length=10, null=True)),
                ('risk_percentage', models.FloatField(blank=True, null=True)),
                ('heart_disease_status', models.CharField(blank=True, max_length=255, null=True)),
                ('anotacoes', models.TextField(blank=True, null=True)),
                ('data_envio', models.DateField(default=datetime.datetime.now)),
                ('horario_envio', models.TimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_dados_pacientes',
            },
        ),
    ]
